name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

      - name: Ensure branch has not advanced since CI
        run: |
          git fetch origin main
          REMOTE_SHA="$(git rev-parse origin/main)"
          CI_SHA="${{ github.event.workflow_run.head_sha }}"
          if [ "$REMOTE_SHA" != "$CI_SHA" ]; then
            echo "main advanced since CI; skipping release."
            exit 0
          fi

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

  docs:
    # Release must be executed first (even if it fails), then we always generate
    # the docs, based on the last commit of the main branch, not the commit that
    # triggered the release.
    needs: release
    if: >
      always() &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'

    concurrency:
      group: docs-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # Force to be the last commit of the main branch (if another commit
          # was pushed in between).
          ref: main

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate docs
        run: npm run docs

      - name: Commit docs
        run: |
          git add -fA ./docs/api
          if git diff --cached --quiet; then
            echo "No doc changes"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "docs: update API reference documentation"
          git push origin HEAD:main

